---
version: '3.8'

services:
  recognizer-backend:
    container_name: recognizer-backend
    platform: linux/x86_64
    restart: always
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ../src:/src
      - ../opt:/opt
    ports:
      - "8093:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8000/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5

  recognizer-frontend:
      build: ./frontend
      ports:
        - "3005:3000"
      depends_on:
        - recognizer-backend
      volumes:
        - ./recognizer-frontend:/app/



